### ISSUE TITLE
Rename `BuildAlloc` to `BuildAllocRef` for consistency?

### ISSUE THREAD

**Issue by scott-maddox** [TimDiekmann/alloc-wg#1]
Awesome work on this repo! You've packed a whole lot of improvements in!

Since you've renamed `Alloc`  to `AllocRef`, do you think it would make sense to change `BuildAlloc` to `BuildAllocRef`?

**Comment by TimDiekmann** [comment]
Thanks!

> Since you've renamed Alloc to AllocRef, do you think it would make sense to change BuildAlloc to BuildAllocRef?

I think that might lead to confusion. You could interpret `BuildAllocRef` as build-`AllocRef` or as `BuildAlloc`-ref. What do you think?

**Comment by scottjmaddox** [comment]
Good point. That is potentially confusing. I think it might be worth it for consistency, though. As soon as you see that it's a trait, that confusion should be cleared up. And since there would no longer be a `BuildAlloc` to reference, `BuildAlloc`-ref probably would not be the default parsing.

(This is the same Scott, btw. Accidentally used work-dedicated account again.)

**Comment by TimDiekmann** [comment]
> As soon as you see that it's a trait, that confusion should be cleared up.

Good point also. I'll rename it to `BuildAllocRef` and wait for feedback if anyone will get confused. At least it's a trivial change and could easily be reverted :)
